- XBVC/emitters/EmitterBase.py
- XBVC/emitters/templates/cobs.py
- XBVC/emitters/templates/py_interface.jinja2
Fixes the generated python to work with python. Doesn't crash with python 3.5.2 but I haven't done any correctness testing.
> Changes to run generated python in python 3

- .gitignore
- XBVC/emitters/c_emitter.py
- test/c_tests/Makefile
- test/c_tests/msgs.yaml
- test/c_tests/test.c
**Don't squash** 
Adds a really unsophisticated C unit test for encoding/decoding round trip.  More to come.
> XBVC: Add unit tests and fix C encoder

- XBVC/emitters/templates/c_header.jinja2
- XBVC/emitters/templates/c_interface.jinja2
- test/c_tests/Makefile
- test/c_tests/msgs.yaml
- test/c_tests/test.c
This now compiles and runs cleanly with -Wall/-Wextra/-Werror
> TEST|C: Fix compiler warnings

- XBVC/emitters/templates/c_interface.jinja2
This gives an error on AVR-GCC
> C: Fix another compiler error

- test/c_tests/Makefile
- test/c_tests/gqueue.c
- test/c_tests/gqueue.h
- test/c_tests/test.c
Ensures that we can encode and decode messages properly.
> TEST: Add roundtrip test for C

- XBVC/emitters/_emitter_registry.py
- XBVC/emitters/nim_emitter.py
- XBVC/emitters/templates/nim_interface.jinja2
- XBVC/objects.py
- test/nim_tests/Makefile
- test/nim_tests/msgs.yaml
- test/nim_tests/test.nim
This is a pretty strait forward nim emitter that requires the bitvec
and cobs libraries to work.  As they will be released on nimble, I
thought this to be an acceptable compromise rather than including
their files here.
> NIM: Add Nim Emitter + Test

- XBVC/emitters/nim_emitter.py
- XBVC/emitters/templates/nim_interface.jinja2
- XBVC/objects.py
- XBVC/xbvcgen.py
- msgs.yaml
- test/c_tests/msgs.yaml
- test/nim_tests/msgs.yaml
- test/nim_tests/test.nim
This replaces some ambiguous/odd syntax in the yaml files with a clear delineation between enums and messages (which allows us to have list enums, which always generate the same way).
Tests pass.
> Add Nim Enums + Make Enum generation deterministic

- XBVC/emitters/templates/nim_interface.jinja2
> NIM: Minor change to close down more cleanly

- XBVC/emitters/templates/nim_interface.jinja2
- test/nim_tests/msgs.yaml
- test/nim_tests/test.nim
This corrects a duplicate variable name from being generated.  
Also: I missed adding float lists to nim the first time around, this is now corrected.
> NIM: Fix bug in floating point decoding

- XBVC/emitters/templates/nim_interface.jinja2
- test/nim_tests/test.nim
This should help avoid gc related issues.
Tested locally
> NIM: Switch to local objects

- XBVC/emitters/templates/nim_interface.jinja2
- test/nim_tests/test.nim
> NIM: Use a non-ref edge point

- XBVC/emitters/templates/nim_interface.jinja2
- test/nim_tests/test.nim
This allows for more flexibility on the host code side as we no longer
require threads to operate.
Tests pass, and also tested in https://github.com/keyme/kiosk/pull/16047
> NIM: Convert to dispatch model

- XBVC/emitters/EmitterBase.py
- XBVC/emitters/c_emitter.py
- XBVC/emitters/nim_emitter.py
- XBVC/emitters/py_emitter.py
- XBVC/emitters/templates/cobs.py
- XBVC/objects.py
- setup.py
Nothing mechanical changed, just formatting.
Tested.
> MISC: Fix all PEP8 violations

- XBVC/emitters/c_emitter.py
There was like 90% similarity here, seemed like a ripe target for
getting this out of a class
> C: Refactor body encode/decode generator functions

- XBVC/emitters/c_emitter.py
- XBVC/emitters/templates/c_header.jinja2
- XBVC/emitters/templates/c_interface.jinja2
- XBVC/emitters/templates/nim_interface.jinja2
- XBVC/objects.py
- test/c_tests/Makefile
- test/c_tests/test.c
- test/nim_tests/test.nim
This will allow responses to specific messages rather than message types.
Needs tested on the kiosk.  Surface level stuff seems to work, but you know how that goes...
> C|NIM|CORE: Add request/reply ID

- XBVC/emitters/c_emitter.py
- XBVC/emitters/templates/c_header.jinja2
- XBVC/emitters/templates/c_interface.jinja2
- XBVC/objects.py
Prevents random autogen cruft from littering our PRs
@knitHacker 
Tested locally
> C: Sort enums and structs

- XBVC/emitters/templates/haskell_core.jinja2
This simplifies the overall operation of the system by eliminating a
long running thread
> HASKELL: Switch from a loop to a data process function

- XBVC/emitters/templates/Cobs.hs
- XBVC/emitters/templates/haskell_core.jinja2
Fixes one of the cobs' error messages and shows the packet information for packets we don't have a handle for. Compiles with IO2. 
> DBG: Add improved debugging information

- XBVC/emitters/templates/Bitvec.hs
- XBVC/emitters/templates/Cobs.hs
- XBVC/emitters/templates/haskell_core.jinja2
- XBVC/emitters/templates/haskell_data.jinja2
@keyme/control-systems-engineers 
Compiles when used in IO2
> Haskell: Fix haskell code to have no warnings in GHC

- XBVC/emitters/c_emitter.py
- XBVC/emitters/haskell_emitter.py
- XBVC/objects.py
> C|HASKELL: Support signed and unsigned 64 bit types

- XBVC/objects.py
- setup.py
We got a warning in our repo about a security risk.  We don't expose
this externally at all (this is a cli tool...) but no reason not to
keep up to date.
Tested locally
> SECURITY: Update Jinja2

- XBVC/emitters/templates/py_interface.jinja2
- setup.py
- test/py_tests/Makefile
- test/py_tests/msgs.yaml
- test/py_tests/test_xbvc.py
@knitHacker 
Tested locally.  I'll be making some additional improvements in an upcoming PR (documentation, renaming classes to fit better w/Python standards, ergonomics, making the core a dispatcher like the haskell client).
> Python: Fix/update python for python3, add basic test
