XBVC/emitters/c_emitter.py
XBVC/emitters/templates/c_interface.jinja2

The C code that was generated previously was very clever with its use
of pointer walking and sorcery.  Unfortunately, the code wasn't very
portable and made a lot of assumptions about things like memory
alignment and sizes of integers.  The new approach uses much more
standard C w/r/t how we decode and encode messages.
Example encode/decode now:
```
int xbvc_encode_set_mono_led(struct x_set_mono_led *src, uint8_t *dest,
int max_len)
{
int index = 0;
index += xbvc_encode_bit_vector(&src->LedId, &dest[index], E_32);
if (index >= max_len) {
return -1;
}
index += xbvc_encode_bit_vector(&src->Intensity, &dest[index], E_32);
if (index >= max_len) {
return -1;
}
index += xbvc_encode_bit_vector(&src->Frequency, &dest[index], E_32);
if (index >= max_len) {
return -1;
}
return index;
}
```
This has …

XBVC: Rethink C emitter

---

XBVC/emitters/templates/c_interface.jinja2

Not everyone needs specific platform init, so it should be OK to allow
NULL here.

C: Allow NULL platform init

---

XBVC/emitters/templates/c_interface.jinja2
test/c_tests/test.c

This is GCC only, but it saves a lot of headache when dealing with
messages which you don't want to handle explicitly (useful during
bringup).
This is effectively how MCUs tend to handle interrupt tables.
Tested locally

C: Add default 'weak' handler

---

XBVC/emitters/templates/nim_interface.jinja2

This appears to be necessary in cases where you have 'gaps' in your
enums. Nim's exhaustiveness checker freaks out and says you haven't
covered all cases.
Tested locally

NIM_EMITTER: Add default discard case to type kind

---

XBVC/emitters/templates/nim_interface.jinja2

Two major changes here:
1) Removed the named 'serialize{X}` functions and utilized a generic
'send' function to reduce boilerplate (and to make things easier down
the line).
2) Added a polling request-response system.  This is optional from a
user's standpoint, but allows blocking response calls in the host side
software, which is very useful for things like checking version
numbers and getting affirmative responses when performing actions
@knithacker, can you have a look?

NIM_EMITTER: Collapse 'serialize' functions. Add response support

---

XBVC/emitters/templates/c_interface.jinja2
XBVC/emitters/templates/nim_interface.jinja2

This is necessary to allow the end user threads to shut down cleanly.  Also fixed a minor issue that can show up in the C emitter when you use -O1

Fix shutdown

---

XBVC/emitters/c_emitter.py
test/c_tests/msgs.yaml
test/c_tests/test.c

ID's were assumed to follow an incremental scheme.  This is not the
case any more and we need to handle it properly.
Tested with new unit test and on an MCU.

C_EMITTER: Fix enum ID mapping

---

XBVC/emitters/templates/c_interface.jinja2
XBVC/emitters/templates/nim_interface.jinja2

This fixes two minor things:
1) The nim decoder now gracefully handles failed decodes and prints out the buffer
2) The C encoder now properly handles U8s (Can't believe I missed that one)
Tested.

NIM/C: Minor bugfixes

---

XBVC/objects.py

This prevents annoying re-ordering of enums during generation
Tested locally

CORE: Sort enums

---

XBVC/emitters/templates/nim_interface.jinja2

Once you close a channel, you can't re-open it due to the underlying memory being deallocated.
This creates new channels on each start.
Tested locally

NIM: Prevent traceback on restarting an edgepoint

---

XBVC/emitters/templates/c_interface.jinja2
XBVC/emitters/templates/nim_interface.jinja2
test/c_tests/msgs.yaml
test/c_tests/test.c
test/nim_tests/test.nim

0.07 would be encoded as 0.7 due to not taking the leading zero into
account.

NIM/C: Fix floating point encoding for numbers with leading zero

---

XBVC/emitters/nim_emitter.py
XBVC/objects.py

Two changes here:
1. Move the nim_types stuff into the nim emitter where it belongs
2. Use a mixin to provide camel/pascal names for objects

CORE: Clean up base objects

---

XBVC/emitters/haskell_emitter.py
XBVC/emitters/templates/Bitvec.hs
XBVC/emitters/templates/haskell_data.jinja2

Moved bitvec to use State and StateT monads to clean up encoding and decoding. Also made an export list for bitvec.
Generated code from this and it compiles and runs.

HASKELL: Use state monad when encoding and decoding bitvecs

---

XBVC/emitters/templates/Cobs.hs
XBVC/emitters/templates/haskell_data.jinja2

In Cobs showing the remaining bytestring was confusing so now showing original bytestring in decode error message. The second change shows what the message ID is that failed to decode for debugging purposes. 

HASKELL: Add more debug info for unmatched messages

---

XBVC/emitters/templates/haskell_core.jinja2

Moves xbvcSend to return a bool for whether it sent successfully and allows an early failure in  xbvcSendWithResponse if the original message fails to send. (If someone were to use this and had a non-blocking send they could just send back a True always)
Works with the changes I made with IO2. 

HASKELL: Move XBVC send functions to use channels with bool return

---

XBVC/emitters/templates/haskell_data.jinja2

We need a way to update local state, this seems like a decent way to
go about it and mirrors our internal communications dispatch (more or less...)

HASKELL: Allow for state to be passed into dispatcher

---

XBVC/emitters/templates/haskell_core.jinja2

Forgot to encode the stand alone send messages. Since we don't get a response we didn't notice they weren't going through if we even have any right now in IO2. 
My branch that needs to send a message works with this change.

HASKELL: Fix xbvcSend to use COBS encoding

---

XBVC/emitters/templates/haskell_core.jinja2

Adds a timeout to the sendWithResponse function so that upstream code can act appropriately if things break

HASKELL: Add timeout to sendWithResponse

---

XBVC/emitters/templates/haskell_core.jinja2

Returns any errors in `processData` function so the function calling it can track how often this happens / log it correctly. 
Modified IO2 and compiled with this. Was able to actually use the `L.error` function to log the errors instead of having them show up in `info`. Also thinking of keeping statistics about what percentage of messages have errors so we have a better way of determining if they are happening more / less often. 

HASKELL: Return any message decoding errors

---

XBVC/emitters/templates/Bitvec.hs

Pointed to this code for example of using the state monad and realized there weren't any docstrings on those not straightforward functions. 

HASKELL: Add doctrings for bitvec code using state monad

---

XBVC/emitters/templates/haskell_core.jinja2
XBVC/emitters/templates/haskell_data.jinja2

This is to potentially curb memory issues. Compiles with the IO2 project. 

HASKELL: Make maps strict

---

XBVC/emitters/templates/py_interface.jinja2
test/py_tests/test_xbvc.py

Cleans things up a bit, better consistency with standard python idioms.
@knitHacker

PYTHON: Make use of pascalcase names, add commentary
